postgres:
  image: postgres:10.19
  ports:
    - '5432:5432'
  container_name: postgres_exchange_rates
  environment:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'postgres'
  volumes:
    - ./init:/docker-entrypoint-initdb.d/